### ISSUE TITLE
Sharick Shekels leaderboard

### ISSUE THREAD

**Issue by mirryi** [stogacs/website#2]
The site needs a leaderboard page to keep track of Sharick Shekel counts.

**Comment by enamchae** [comment]
Where is shekel data stored? If it's in an Excel file, would a separate database server be appropriate for this?

**Comment by mirryi** [comment]
It's currently in a Google Sheet, and one option would be to store and update a well-formed CSV or JSON file with this data in-tree. Each record would have:

-   Name
-   Zero or more integers indicating the number of Shekels earned per week

Using something like [`csv-loader`](https://github.com/theplatapi/csv-loader) or Webpack's built-in JSON loader, the data would be imported at compile-time and emitted within the bundle.

If we want to avoid storing this kind of data in-tree, we can spin up a database and web API to request to. However, we'd have to then host this server somewhere.

**Comment by enamchae** [comment]
Since you're using Sheets, we could probably use the [Sheets API](https://developers.google.com/sheets/api/guides/concepts), if we wanted to avoid opening a server or storing the data statically.

I guess with this route there could be problems with [quota](https://developers.google.com/sheets/api/limits) and privacy (if there are full names or personal information on the sheet, which would probably need to be shared to "anyone with the link"). The Sheets API quota doesn't appear to be too strict for our purposes, though.

Another problem could be the API key, which would need to be embedded in the page. I don't believe there's much we could do on that front other than restrict the referrer URL on the key. I'm not sure this is much cause for concern either way, but there it is anyway. Google has also sometimes limited/disabled YouTube Data API keys that aren't used in a while, though I don't know whether that applies to Sheets API projects too.

**Comment by mirryi** [comment]
Frankly, the Google Sheet is just a temporary solution more than anything. Ideally, nothing should depend on Google Drive or anyone's Google account. We should strive to have all infrastructure in this GitHub organization.

Using the Sheets API should be last resort, but I don't think it will come to that.
